name: Deploy

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache NuGet packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.x

      - name: Cache .NET Workload Tools
        uses: actions/cache@v3
        with:
          path: ~/.dotnet
          key: ${{ runner.os }}-dotnet-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-dotnet-

      - name: Check if wasm-tools are installed
        run: |
          if ! dotnet --list-runtimes | grep -q 'Microsoft.NETCore.App'; then
            echo "Installing wasm-tools..."
            dotnet workload install wasm-tools
          else
            echo "wasm-tools already installed"
          fi

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build and Publish .NET
        run: dotnet publish BlazorPWA.csproj -c Release -o docs --no-restore --no-build --nologo

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload
        uses: actions/upload-pages-artifact@v3
        with: 
          path: 'docs/wwwroot'

      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
name: Deploy

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache NuGet packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.x

      - name: Cache .NET Workload Tools
        uses: actions/cache@v3
        with:
          path: ~/.dotnet
          key: ${{ runner.os }}-dotnet-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-dotnet-

      - name: Check if wasm-tools are installed
        run: |
          if ! dotnet --list-runtimes | grep -q 'Microsoft.NETCore.App'; then
            echo "Installing wasm-tools..."
            dotnet workload install wasm-tools
          else
            echo "wasm-tools already installed"
          fi

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build and Publish .NET
        run: dotnet publish BlazorPWA.csproj -c Release -o docs --no-restore --no-build --nologo

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload
        uses: actions/upload-pages-artifact@v3
        with: 
          path: 'docs/wwwroot'

      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
